# Problem 12
#
# The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:
# 1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...
# Let us list the factors of the first seven triangle numbers:
#  1: 1
#  3: 1,3
#  6: 1,2,3,6
# 10: 1,2,5,10
# 15: 1,3,5,15
# 21: 1,3,7,21
# 28: 1,2,4,7,14,28
# We can see that 28 is the first triangle number to have over five divisors.
# What is the value of the first triangle number to have over five hundred divisors?

require "./helper.rb"

def divisorsOf(n)
  divisors = []
  (1..((n**0.5).round + 1)).each do |i|
    quotient = n / i
    remainder = n % i
    if remainder == 0
      if quotient >= i
        divisors.push(i)
        if quotient > i
          divisors.push(n/i)
        end
      end
    end
  end
  divisors.push(n)
  return divisors
end

i = 1
n = 1

while divisorsOf(n).count < 500 do
  i += 1
  n += i
end

puts n
